Repository kyma-project/cloud-manager-tests, pull requests merged in 2024-09, with the labels that each got.

#27 chore: big cleanup timeout
  internal/noCloudResources.go
Labels: lgtm, size/XS, cla: yes

#28 test(AwsRedisInstance): add AwsRedisInstance feature test
  features/300-awsredisinstance.feature
Labels: lgtm, size/M, cla: yes

#29 chore: increase aws redis deletion timeout
  features/300-awsredisinstance.feature
  internal/register.go
  internal/resourceDoesNotExist.go
Labels: lgtm, size/M, cla: yes

#30 test (GcpNfsBackupSchedule): e2e test
  features/200-gcpnfs-backup-schedule.feature
Labels: lgtm, size/M, cla: yes

#31 GcpNfsBackupSchedule e2e test fix
  features/200-gcpnfs-backup-schedule.feature
  internal/register.go
  internal/valueAssert.go
Labels: lgtm, size/M, cla: yes

#34 test(GcpNfsBackupSchedule): e2e tests
  features/000-module.feature
  features/200-gcpnfs-backup-schedule.feature
  internal/register.go
  internal/valueAssert.go
Labels: lgtm, size/L, cla: yes

#35 test: add GcpNfsVolume backup/restore features
  features/200-gcpnfsvolumebackup.feature
  features/200-gcpnfsvolumerestore-newvolume.feature
  features/200-gcpnfsvolumerestore.feature
Labels: lgtm, size/L, cla: yes

#36 test: combining all NFS related tests for gcp to reduce execution time
  features/200-gcpnfsvolume.feature
  features/200-gcpnfsvolumebackup.feature
  features/200-gcpnfsvolumerestore-newvolume.feature
  features/200-gcpnfsvolumerestore.feature
Labels: lgtm, size/L, cla: yes
