Repository kyma-project/cloud-manager-tests, pull requests merged in 2024-10, with the labels that each got.

#39 updating aws skr
  assets/config.json
Labels: lgtm, size/XS, cla: yes

#40 kubeconfig debug
  .github/workflows/e2e.yml
Labels: lgtm, size/XS, cla: yes

#41 debug token
  .github/workflows/e2e.yml
Labels: lgtm, size/XS, cla: yes

#42 kubeconfig debug
  .github/workflows/e2e.yml
Labels: lgtm, size/XS, cla: yes

#43 chore: update Redis API
  features/300-awsredisinstance.feature
  features/300-gcpredisinstance.feature
Labels: lgtm, size/XS, cla: yes

#44 test(AwsVpcPeering): e2e tests
  features/400-awsvpcpeering.feature
Labels: lgtm, size/M, cla: yes

#45 test(AwsVpcPeering): switch to alpine image
  features/400-awsvpcpeering.feature
Labels: lgtm, size/S, cla: yes

#46 test(GcpNfsBackupSchedule): merged with GcpNfsVolume feature
  features/200-gcpnfs-backup-schedule.feature
  features/200-gcpnfsvolume.feature
Labels: lgtm, size/M, cla: yes

#48 test(AwsVpcPeering): adding pod restartPolicy Never
  features/400-awsvpcpeering.feature
Labels: lgtm, size/XS, cla: yes

#49 feat(AzureRedis): e2e test
  assets/config.json
  features/000-module.feature
  features/300-azureredisinstance.feature
Labels: lgtm, size/M, cla: yes

#52 test(AzureVpcPeering): e2e tests
  features/500-azurevpcpeering.feature
Labels: lgtm, size/M, cla: yes

#51 chore(GCP Vpc Peering) Adding GCPVP e2e tests
  features/400-gcpvpcpeering.feature
Labels: lgtm, size/M, cla: yes

#54 chore: Azure ca update
  assets/config.json
Labels: lgtm, size/XS, cla: yes

#55 chore(AwsRedisInstance) add readReplica
  features/300-awsredisinstance.feature
Labels: lgtm, size/XS, cla: yes

#56 test: Azure c-6488bcc
  assets/config.json
Labels: lgtm, size/XS, cla: yes

#58 test: add AwsNfsVolume backup/restore features
  features/000-module.feature
  features/200-awsnfsvolume.feature
  features/200-gcpnfsvolume.feature
Labels: size/M, cla: yes

#60 chore(GCP Vpc Peering) Fixing field
  features/400-gcpvpcpeering.feature
Labels: lgtm, size/XS, cla: yes

#61 test: e2e test for AwsNfsBackupSchedule
  features/200-awsnfsvolume.feature
Labels: size/S, cla: yes

#53 update usage section
  README.md
Labels: lgtm, size/M, cla: yes

#62 chore: fixing lint-check version and cleaning up e2e test pods
  .github/workflows/lint-markdown-links.yml
  internal/k8s.go
  internal/noCloudResources.go
  internal/resourceApplied.go
Labels: lgtm, size/S, cla: yes
