Repository kyma-project/cloud-manager-tests, pull requests merged in 2024-08, with the labels that each got.

#20 E2e
  .github/workflows/e2e.yml
  assets/config.json
  assets/rbac.yaml
  cmd/main.go
  features/000-module.feature
  features/200-awsnfsvolume.feature
  features/200-gcpnfsvolume.feature
  features/global.js
  features/main.feature
  features/module.feature
  go.mod
  go.sum
  internal/cloudResourcesPriority.go
  internal/cloudResourcesPriority_test.go
  internal/crdsExist.go
  internal/ctx.go
  internal/k8s.go
  internal/module.go
  internal/noCloudResources.go
  internal/register.go
  internal/resourceApplied.go
  internal/resourceDeleted.go
  internal/script.go
Labels: lgtm, size/XXL, cla: yes

#21 StopOnFailure true
  cmd/main.go
Labels: lgtm, size/XS, cla: yes

#22 chore: increase GcpNfsVolume ready timeout
  cmd/main.go
  features/200-awsnfsvolume.feature
  internal/register.go
  internal/timeout.go
  internal/valueAssert.go
Labels: lgtm, size/M, cla: yes

#23 chore: increase GcpNfsVolume ready timeout .
  internal/valueAssert.go
Labels: lgtm, size/M, cla: yes

#24 test(GcpRedisInstance): add GcpRedisInstance feature test
  .gitignore
  features/200-awsnfsvolume.feature
  features/200-gcpnfsvolume.feature
  features/300-gcpredisinstance.feature
Labels: lgtm, size/M, cla: yes

#25 chore: adjust timeout
  features/300-gcpredisinstance.feature
  internal/timeout.go
Labels: lgtm, size/XS, cla: yes

#26 change redis version
  features/300-gcpredisinstance.feature
Labels: lgtm, size/XS, cla: yes
