Repository kyma-project/cloud-manager-tests, pull requests merged in 2024-11, with the labels that each got.

#63 test: update redis manifests
  features/300-awsredisinstance.feature
  features/300-azureredisinstance.feature
  features/300-gcpredisinstance.feature
Labels: lgtm, size/XS, cla: yes

#65 Update module.go
  internal/module.go
Labels: size/XS, cla: yes

#66 Update module.go
  internal/module.go
Labels: size/XS, cla: yes

#67 Update 300-azureredisinstance.feature
  features/300-azureredisinstance.feature
Labels: lgtm, size/XS, cla: yes

#68 Update 300-awsredisinstance.feature
  features/300-awsredisinstance.feature
Labels: size/XS, cla: yes

#69 chore: SKRs c-4de88ef, a2f3c8f, c-6ea9b9b
  assets/config.json
Labels: lgtm, size/S, cla: yes
